[package]
name = "arcs"
version = "0.1.0"
authors = ["Örjan Ekeberg <ekeberg@kth.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
structopt = { version = "0.3", default-features = false }
